#  appveyor.yml
install:
  - cinst winflexbison
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - curl -S -O https://buildfarm.postgresql.org/downloads/latest-client.tgz
  - tar -z -tvf latest-client.tgz
  - mkdir \bf
  - tar --directory=c:/bf -z --strip-components=1 -xf latest-client.tgz
  - move latest-client.tgz \bf
  - curl -S -O https://raw.githubusercontent.com/PGBuildFarm/appveyor-build/master/build-farm.conf
  
before_build:
  - rename c:\ProgramData\chocolatey\bin\win_flex.exe flex.exe
  - rename c:\ProgramData\chocolatey\bin\win_bison.exe bison.exe
  - perl -spi.bak -e '/# check what sort of build we are doing/ && print "exit 0 if ($ARGV[0] && $ARGV[0] eq q{PROJECTONLY});\n"' src/tools/msvc/build.pl
  - perl /bf/run_build.pl --only-steps=configure
  - perl src/tools/msvc/build.pl PROJECTONLY
  - per -spi.bak -e 's/^(test: tablespace)/# $1/;' src/test/regress/parallel_schedule
  - mkdir buildroot

build:
  project: pgsql.sln
  
configuration:
  - Release


test_script:
  - perl /bf/run_build.pl --skip-steps="configure make"


