#  appveyor.yml
install:
  - cinst winflexbison
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - curl -S -O https://buildfarm.postgresql.org/downloads/latest-client.tgz
  - tar -z -tvf latest-client.tgz
  - mkdir \bf
  - move latest-client.tgz \bf
  - dir \bf
  - tar --version
  - tar -C /bf -z --strip-components=1 -xf /bf/latest-client.tgz
  - mkdir buildroot
  - copy \bf\build-farm.conf.sample build-farm.conf
  - perl -spi.bak -e 's/build_root => undef/build_root => "\$confdir/buildroot"/; s/# (?=\$PGBuild::Options::from_source = \$confdir;)//;' build-farm.conf
  - grep confdir build-farm.conf
  
before_build:
  - rename c:\ProgramData\chocolatey\bin\win_flex.exe flex.exe
  - rename c:\ProgramData\chocolatey\bin\win_bison.exe bison.exe
  
test_script:
  - dir
